select SYSTEM_LOGIN,
    	dn,	

		case when substring(MOST_FREQUENT_CLIENT,2,3) = 'RCH' then '500 Enterprise Dr'
			when substring(MOST_FREQUENT_CLIENT,2,3) = '282' then '282 Washington St'
			else substring(MOST_FREQUENT_CLIENT,2,3)
			end as STaddress
			,MOST_FREQUENT_CLIENT

  from #AdLoc
  order by MOST_FREQUENT_CLIENT









--select
--SYSTEM_LOGIN,DISTINGUISHED_NAME as dn 
--,max(MOST_FREQUENT_CLIENT) as MOST_FREQUENT_CLIENT
--into #AdLoc
--from
--(
--	select USER_ID,EPIC_USER_NAME,SYSTEM_LOGIN,DISTINGUISHED_NAME,AD_DEPARTMENT,TITLE,EMPLOYEE_ID,USER_ACCOUNT_CONTROL
--	,case when row_number() over (partition by USER_ID order by LOGIN_COUNT_BY_DEPT desc) = 1 then LOGIN_DEPARTMENT end MOST_FREQUENT_LOGIN_DEPARTMENT
--	,case when row_number() over (partition by USER_ID order by LOGIN_COUNT_BY_CLIENT desc) = 1 then CLIENTNAME end MOST_FREQUENT_CLIENT
--	,case when row_number() over (partition by USER_ID order by MOST_RECENT_LOGIN desc) = 1 then LOGIN_DEPARTMENT end MOST_RECENT_LOGIN_DEPARTMENT
--	,case when row_number() over (partition by USER_ID order by MOST_RECENT_LOGIN desc) = 1 then CLIENTNAME end MOST_RECENT_CLIENT
--	from
--	(
--		select USER_ID,EPIC_USER_NAME,SYSTEM_LOGIN,DISTINGUISHED_NAME,AD_DEPARTMENT,TITLE,EMPLOYEE_ID,USER_ACCOUNT_CONTROL
--		,LOGIN_DEPARTMENT,CLIENTNAME
--		,sum(count(*)) over (partition by USER_ID,LOGIN_DEPARTMENT) LOGIN_COUNT_BY_DEPT
--		,sum(count(*)) over (partition by USER_ID,CLIENTNAME) LOGIN_COUNT_BY_CLIENT
--		,max(ACCESS_TIME) MOST_RECENT_LOGIN
--		from
--		(
--			select WRK.USER_ID,EMP.NAME EPIC_USER_NAME,USR.SYSTEM_LOGIN,USR.DISTINGUISHED_NAME,USR.DEPARTMENT_NAME AD_DEPARTMENT
--			,USR.TITLE,USR.EMPLOYEE_ID,USR.USER_ACCOUNT_CONTROL,WRK.ACCESS_TIME
--			,case when CLI.STRING_VALUE like '%/%'
--				then right(CLI.STRING_VALUE,len(CLI.STRING_VALUE)-charindex('/',CLI.STRING_VALUE))
--				else CLI.STRING_VALUE
--			end CLIENTNAME
--			,DEP.DEPARTMENT_NAME LOGIN_DEPARTMENT
--			from ACCESS_WRKF WRK
--			inner join ACCESS_WRKF_DTL CLI on CLI.ACCESS_INSTANT = WRK.ACCESS_INSTANT
--				and CLI.PROCESS_ID = WRK.PROCESS_ID and CLI.DATA_MNEMONIC_ID = 'CLIENTNAME'
--			left outer join ACCESS_WRKF_DTL LDP on LDP.ACCESS_INSTANT = WRK.ACCESS_INSTANT
--				and LDP.PROCESS_ID = WRK.PROCESS_ID and LDP.DATA_MNEMONIC_ID = 'DEP'
--			left outer join X_D_SEC_USERS_IN_AD USR on USR.USER_ID = WRK.USER_ID
--			left outer join CLARITY_DEP DEP on DEP.DEPARTMENT_ID = LDP.INTEGER_VALUE
--			left outer join CLARITY_EMP EMP on EMP.USER_ID = WRK.USER_ID
--			where WRK.METRIC_ID = 14010 and WRK.PROCESS_ID like 'prd%'
--				and WRK.ACCESS_INSTANT >= '5499499798.273902'
--		) VW
--		group by USER_ID,EPIC_USER_NAME,SYSTEM_LOGIN,DISTINGUISHED_NAME,AD_DEPARTMENT,TITLE,EMPLOYEE_ID,USER_ACCOUNT_CONTROL
--		,LOGIN_DEPARTMENT,CLIENTNAME
--	) VW
--) VW
--group by USER_ID,EPIC_USER_NAME,SYSTEM_LOGIN,DISTINGUISHED_NAME,AD_DEPARTMENT,TITLE,EMPLOYEE_ID,USER_ACCOUNT_CONTROL